"""
Stripe Connect Routes for Real Money Operations
Handles account creation, onboarding, bank accounts, deposits, and withdrawals
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional, Dict
import logging

from database import get_db
from models import User
from auth import get_current_user
from services.stripe_service import StripePaymentService

router = APIRouter(prefix="/stripe-connect", tags=["Stripe Connect"])
logger = logging.getLogger(__name__)


class CreateAccountRequest(BaseModel):
    country: str = "US"
    business_type: str = "individual"  # individual or company


class OnboardingLinkRequest(BaseModel):
    refresh_url: str
    return_url: str


class BankAccountRequest(BaseModel):
    bank_token: str  # Generated by Stripe.js


class DepositRequest(BaseModel):
    amount: float
    payment_method_id: str  # Stripe payment method ID


class WithdrawRequest(BaseModel):
    amount: float


@router.post("/create-account")
async def create_stripe_account(
    request: CreateAccountRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create a Stripe Connect account for the user.
    This is automatically called during signup but can be called manually if needed.
    """
    try:
        # Check if user already has a Stripe account
        if current_user.stripe_account_id:
            return {
                "message": "Stripe account already exists",
                "stripe_account_id": current_user.stripe_account_id,
                "onboarding_required": False
            }
        
        # Create Stripe Connect account
        result = await StripePaymentService.create_connected_account(
            user_id=current_user.id,
            email=current_user.email,
            country=request.country
        )
        
        # Save Stripe account ID to database
        current_user.stripe_account_id = result["stripe_account_id"]
        db.commit()
        
        logger.info(f"Created Stripe account for user {current_user.id}: {result['stripe_account_id']}")
        
        return {
            "message": "Stripe account created successfully",
            "stripe_account_id": result["stripe_account_id"],
            "onboarding_required": True
        }
        
    except Exception as e:
        logger.error(f"Failed to create Stripe account: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/onboarding-link")
async def get_onboarding_link(
    request: OnboardingLinkRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Generate Stripe Connect onboarding link for user to complete setup.
    User will verify identity, add bank account, etc.
    """
    try:
        if not current_user.stripe_account_id:
            raise HTTPException(
                status_code=400,
                detail="No Stripe account found. Please create account first."
            )
        
        # Generate onboarding link
        onboarding_url = await StripePaymentService.create_account_link(
            stripe_account_id=current_user.stripe_account_id,
            refresh_url=request.refresh_url,
            return_url=request.return_url
        )
        
        logger.info(f"Generated onboarding link for user {current_user.id}")
        
        return {
            "onboarding_url": onboarding_url,
            "message": "Complete onboarding to enable deposits and withdrawals"
        }
        
    except Exception as e:
        logger.error(f"Failed to generate onboarding link: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/account-status")
async def get_account_status(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Check the status of user's Stripe Connect account.
    Returns whether onboarding is complete and account is ready for transactions.
    """
    try:
        if not current_user.stripe_account_id:
            return {
                "connected": False,
                "onboarding_complete": False,
                "charges_enabled": False,
                "payouts_enabled": False,
                "message": "No Stripe account connected"
            }
        
        # Get account details from Stripe
        status = await StripePaymentService.get_account_status(
            current_user.stripe_account_id
        )
        
        return {
            "connected": True,
            "stripe_account_id": current_user.stripe_account_id,
            **status
        }
        
    except Exception as e:
        logger.error(f"Failed to get account status: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/add-bank-account")
async def add_bank_account(
    request: BankAccountRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Add a bank account to user's Stripe Connect account.
    Bank token is generated on frontend using Stripe.js
    """
    try:
        if not current_user.stripe_account_id:
            raise HTTPException(
                status_code=400,
                detail="No Stripe account found. Please create account first."
            )
        
        result = await StripePaymentService.add_bank_account(
            user_id=current_user.id,
            stripe_account_id=current_user.stripe_account_id,
            bank_token=request.bank_token
        )
        
        logger.info(f"Added bank account for user {current_user.id}")
        
        return {
            "message": "Bank account added successfully",
            **result
        }
        
    except Exception as e:
        logger.error(f"Failed to add bank account: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/bank-accounts")
async def list_bank_accounts(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    List all bank accounts connected to user's Stripe account.
    """
    try:
        if not current_user.stripe_account_id:
            return {"bank_accounts": []}
        
        accounts = await StripePaymentService.list_bank_accounts(
            current_user.stripe_account_id
        )
        
        return {"bank_accounts": accounts}
        
    except Exception as e:
        logger.error(f"Failed to list bank accounts: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/deposit")
async def deposit_money(
    request: DepositRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Deposit real money from user's bank account into their wallet.
    This charges their payment method and adds funds to wallet balance.
    """
    try:
        if request.amount <= 0:
            raise HTTPException(status_code=400, detail="Amount must be positive")
        
        if not current_user.stripe_account_id:
            raise HTTPException(
                status_code=400,
                detail="No Stripe account found. Please complete onboarding first."
            )
        
        # Process deposit via Stripe
        result = await StripePaymentService.process_deposit(
            user_id=current_user.id,
            amount=request.amount,
            payment_method_id=request.payment_method_id,
            stripe_account_id=current_user.stripe_account_id
        )
        
        # Add funds to wallet balance
        current_user.balance += request.amount
        db.commit()
        
        logger.info(f"User {current_user.id} deposited ${request.amount}")
        
        return {
            "message": f"Successfully deposited ${request.amount:.2f}",
            "transaction_id": result["transaction_id"],
            "amount": request.amount,
            "new_balance": current_user.balance,
            "status": result["status"]
        }
        
    except Exception as e:
        logger.error(f"Deposit failed: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/withdraw")
async def withdraw_money(
    request: WithdrawRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Withdraw money from wallet to user's bank account.
    This deducts from wallet balance and transfers to their bank via Stripe.
    """
    try:
        if request.amount <= 0:
            raise HTTPException(status_code=400, detail="Amount must be positive")
        
        if request.amount > current_user.balance:
            raise HTTPException(
                status_code=400,
                detail=f"Insufficient balance. Available: ${current_user.balance:.2f}"
            )
        
        if not current_user.stripe_account_id:
            raise HTTPException(
                status_code=400,
                detail="No Stripe account found. Please complete onboarding first."
            )
        
        # Process withdrawal via Stripe
        result = await StripePaymentService.process_withdrawal(
            user_id=current_user.id,
            amount=request.amount,
            stripe_account_id=current_user.stripe_account_id
        )
        
        # Deduct from wallet balance
        current_user.balance -= request.amount
        db.commit()
        
        logger.info(f"User {current_user.id} withdrew ${request.amount}")
        
        return {
            "message": f"Successfully withdrew ${request.amount:.2f}",
            "transaction_id": result["transaction_id"],
            "amount": request.amount,
            "new_balance": current_user.balance,
            "status": result["status"],
            "estimated_arrival": result.get("estimated_arrival", "2-3 business days")
        }
        
    except Exception as e:
        logger.error(f"Withdrawal failed: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/transactions")
async def get_stripe_transactions(
    limit: int = Query(10, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get history of Stripe deposits and withdrawals for the user.
    """
    try:
        if not current_user.stripe_account_id:
            return {"transactions": []}
        
        transactions = await StripePaymentService.get_transaction_history(
            stripe_account_id=current_user.stripe_account_id,
            limit=limit
        )
        
        return {"transactions": transactions}
        
    except Exception as e:
        logger.error(f"Failed to get transactions: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/setup-intent")
async def create_setup_intent(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create a setup intent for saving payment methods.
    Used when users want to add cards/bank accounts for future deposits.
    """
    try:
        import stripe
        
        # Create or get Stripe customer
        if not current_user.stripe_customer_id:
            customer = stripe.Customer.create(
                email=current_user.email,
                name=current_user.full_name,
                metadata={"user_id": str(current_user.id)}
            )
            current_user.stripe_customer_id = customer.id
            db.commit()
        
        # Create setup intent
        setup_intent = stripe.SetupIntent.create(
            customer=current_user.stripe_customer_id,
            payment_method_types=["card"],
        )
        
        return {
            "client_secret": setup_intent.client_secret,
            "setup_intent_id": setup_intent.id
        }
        
    except Exception as e:
        logger.error(f"Failed to create setup intent: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/deposit-intent")
async def create_deposit_intent(
    request: DepositRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create a payment intent for deposits.
    Returns client secret for Stripe payment sheet.
    """
    try:
        import stripe
        
        if request.amount <= 0:
            raise HTTPException(status_code=400, detail="Amount must be positive")
        
        if request.amount < 1:
            raise HTTPException(status_code=400, detail="Minimum deposit is $1.00")
        
        # Create or get Stripe customer
        if not current_user.stripe_customer_id:
            customer = stripe.Customer.create(
                email=current_user.email,
                name=current_user.full_name,
                metadata={"user_id": str(current_user.id)}
            )
            current_user.stripe_customer_id = customer.id
            db.commit()
        
        # Create ephemeral key
        ephemeral_key = stripe.EphemeralKey.create(
            customer=current_user.stripe_customer_id,
            stripe_version="2024-11-20.acacia",
        )
        
        # Create payment intent
        amount_cents = int(request.amount * 100)
        payment_intent = stripe.PaymentIntent.create(
            amount=amount_cents,
            currency="usd",
            customer=current_user.stripe_customer_id,
            automatic_payment_methods={"enabled": True},
            metadata={
                "user_id": str(current_user.id),
                "type": "deposit"
            }
        )
        
        return {
            "client_secret": payment_intent.client_secret,
            "ephemeral_key": ephemeral_key.secret,
            "customer_id": current_user.stripe_customer_id,
            "payment_intent_id": payment_intent.id,
            "payment_method_id": payment_intent.payment_method
        }
        
    except Exception as e:
        logger.error(f"Failed to create deposit intent: {e}")
        raise HTTPException(status_code=500, detail=str(e))

